# Generated by Django 4.0.5 on 2022-07-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='spacies',
            new_name='species',
        ),
    ]
